[tool.kedro]
package_name = "clincial_research_workflow"
project_name = "Clinical Research Workflow"
project_version = "0.17.3"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_third_party = "kedro"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/clincial_research_workflow -ra"""
